### ISSUE TITLE
Beta 3 1.17.1 Fabric Crash server

### ISSUE THREAD

**Issue by itsdinkd** [daPoseidonGuy/strawgolem#55]
Randomly crashing server

https://pastebin.com/NchyADu9

**Comment by red2blue** [comment]
Getting another OctTree crash :( 
https://pastebin.com/P9SeavrD
@t2pellet

**Comment by t2pellet** [comment]
@red2blue does this crash occur regularly, or was it a 1 off?

Stacktrace for this one is a bit weird, as it doesn't really point anywhere. Looking at the crash, it seems the server watchdog killed the server. This normally happens when there's a significant amount of lag / the server is hanging.

Any additional info you might have would be helpful! If the issue occurs often, it might be worth trying without Not Enough Crashes, just to see what the stacktrace looks like without it.

**Comment by red2blue** [comment]
It's pretty frequent. I unfortunately cannot tell you what happens as I am not on the server when it happens, I am looking at crash logs. 

The post from 7 days ago is from Beta 4, post from 2 days ago is Beta 5.

**Comment by t2pellet** [comment]
Try with the build linked here:

https://github.com/t2pellet/strawgolem/issues/60#issuecomment-958105736

It might fix the issue, if not, the stacktrace should be slightly more informative with this build.

**Comment by red2blue** [comment]
Still crashed. 


https://pastebin.com/PMdpQtjm
